# Android toolchain, arm64-v8a only, NDK r25b and newer
set(CMAKE_SYSTEM_NAME Android)
set(CMAKE_SYSTEM_VERSION 29)
set(CMAKE_SYSTEM_PROCESSOR aarch64)
set(ANDROID_ABI arm64-v8a)

# NDK detection: -DNDK, env ANDROID_NDK / ANDROID_NDK_HOME, or ../ndk/android-ndk-r*
if(NOT DEFINED NDK)
  if(DEFINED ENV{ANDROID_NDK})
    set(NDK $ENV{ANDROID_NDK})
  elseif(DEFINED ENV{ANDROID_NDK_HOME})
    set(NDK $ENV{ANDROID_NDK_HOME})
  else()
    get_filename_component(_THIS_DIR "${CMAKE_CURRENT_LIST_FILE}" DIRECTORY)
    get_filename_component(ROOT "${_THIS_DIR}/.." ABSOLUTE)
    file(GLOB NDK_CANDIDATES "${ROOT}/ndk/android-ndk-r*")
    if(NDK_CANDIDATES)
      list(SORT NDK_CANDIDATES)
      list(GET NDK_CANDIDATES -1 NDK)
    else()
      set(NDK "${ROOT}/ndk/android-ndk-r25b")
    endif()
  endif()
endif()

if(EXISTS "${NDK}/toolchains/llvm/prebuilt/linux-x86_64/sysroot")
  set(NDK_SYSROOT "${NDK}/toolchains/llvm/prebuilt/linux-x86_64/sysroot")
else()
  set(NDK_SYSROOT "${NDK}/toolchains/llvm/prebuilt/linux-x86_64/sysroot")
endif()

get_filename_component(_THIS_DIR "${CMAKE_CURRENT_LIST_FILE}" DIRECTORY)
if(EXISTS "${_THIS_DIR}/android-clang")
  set(CMAKE_C_COMPILER "${_THIS_DIR}/android-clang")
  set(CMAKE_CXX_COMPILER "${_THIS_DIR}/android-clang++")
else()
  set(CMAKE_C_COMPILER "${NDK}/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android29-clang")
  set(CMAKE_CXX_COMPILER "${NDK}/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android29-clang++")
endif()

set(CMAKE_FIND_ROOT_PATH "${NDK_SYSROOT}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
set(CMAKE_ANDROID_ARCH_ABI arm64-v8a)
